### PR TITLE
Added sample code for API:Emailuser 

### LINKED ISSUE #56: Add sample code for send an email to demonstrate the use of API:Emailuser module
An email can be sent to users who have a confirmed email address. The API:Emailuser module page hasn't a code sample to demonstrate this action.It is good to develop code sample for this.

The link of action API:Emailuser module is : https://www.mediawiki.org/wiki/API:Emailuser

### PR DESCRIPTION
**Pull request by silkypriya**
Fixes #56 
An email can be sent by a user to another users using action API:Emailuser module.
This sample code is to demonstrate this.

### CODE REVIEW

**Comment by silkypriya** [comment]
Hello @srish ,I made the commit after update and test with Pylint.
I look forward to hearing from you.Thank you!

**Comment by srish** [comment]
@silkypriya Here is first round of feedback: https://www.mediawiki.org/wiki/Topic:Uv9mpwzufehhffe5 :)

**Comment by silkypriya** [comment]
Thank you @srish for feedback and suggested improvements.I made the changes and this is the link(https://www.mediawiki.org/wiki/User:Silky44/Sandbox/API:Emailuser) of the modified document. Please let me know,if more changes are required. 
Thank you!

**Comment by srish** [comment]
@silkypriya Thanks for your work on this! this is ready https://www.mediawiki.org/wiki/User:Silky44/Sandbox/API:Emailuser. You can move this to main namespace as well and remember to leave a comment before publishing changes :)

Overall the documentation looks good! I made minor changes: added POST request, and removed translation markers.. read https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_example#Step_4:_Making_changes.

**Comment by silkypriya** [comment]
Thank you @srish

**Pull request merged**
