### PR TITLE
adds code to autogenerate js files

### PR DESCRIPTION
**Pull request by shivanshbindal9**
This adds code to auto generate javascript files and also various file autogenerated by this code.
Here, ```fetch``` is used to make asynchronous api requests. The outputs of these files can be seen by running these code snippets in developers console. Some of these files generated may not function properly as some changes are needed in the modules.json.

### CODE REVIEW

**Comment by shivanshbindal9** [comment]
@srish now there is only one autogenerator for both python and javascript files and is present inside the ```python``` directory. Since, now we have separate directory for autogenerated javascript files we should move the ```autogenerator.py``` file to the base directory as this will be more intuitive to anyone autogenerating the code that the generated code is will go both in ```python``` and ```javascript``` directories.

**Comment by shivanshbindal9** [comment]
@srish I have made all the changes, can you please review. Thanks :)

**Comment by srish** [comment]
@shivanshbindal9 Neat work! Almost there :-) One small change to make and more thing to investigate:
* Filenames in all JS files have py extension still.
* All JS files with endpoint as `http://mediawiki.org/w/api.php` are resulting in type error and not showing any results. Could you maybe look into that? It may have something to do with https://www.mediawiki.org/wiki/API:Cross-site_requests but I am not sure.

**Comment by shivanshbindal9** [comment]
@srish as mentioned in https://www.mediawiki.org/wiki/API:Cross-site_requests I have already supplied origin parameter in all the request. I noticed that the urls start working once ```www``` is appended at their beginning.

**Comment by srish** [comment]
@shivanshbindal9 great! thanks for looking into that :) you can then just fix the extension name in files and I will merge this pull request.

**Comment by shivanshbindal9** [comment]
@srish thanks for your reviews and suggestions :). I have changed the files extension in JS files.

**Comment by srish** [comment]
@shivanshbindal9 super neat work! thanks a lot :)

**Pull request merged**
