### PR TITLE
Sample code for API:RecentChanges

### PR DESCRIPTION
**Pull request by brendajerop**
Sample code for API:RecentChanges module to get the three most recent changes with sizes and flags.

### CODE REVIEW

**Comment by Abhishekism9450** [comment]
@brendajerop Can you add the documentation for the same in README also.

**Comment by brendajerop** [comment]
@Abhishekism9450 Ok. Thanks:)

**Comment by brendajerop** [comment]
@srish Thanks for your feedback! I've made the changes as requested and [my documentation](https://www.mediawiki.org/wiki/User:Jeropbrenda/Sandbox/API:RecentChanges) is ready to go live:)

**Comment by srish** [comment]
This is ready: https://www.mediawiki.org/wiki/User:Jeropbrenda/Sandbox/API:RecentChanges :) I've made minor changes. You can move this to API:Recent changes, when you add your changes make sure you say in the comment: "updated as per the improving the action API documentation project". For reference check following page's history as it recently got updated: https://www.mediawiki.org/w/index.php?title=API:Move&action=history. Let me know if you've any trouble while doing so :)

**Pull request merged**
