### PR TITLE
API:Links sample code to get red links in a page

### PR DESCRIPTION
**Pull request by brendajerop**
Sample code to demonstrate the use of API:Links module to identify red links on a page.
Based on #37

### CODE REVIEW

**Comment by srish** [comment]
Thanks for working on this! Give me 1-2 days time to review your work!

**Comment by brendajerop** [comment]
@srish Thanks for the feedback! I've made changes as required

**Comment by brendajerop** [comment]
@srish Thanks for the feedback! Made the changes as requested

**Comment by brendajerop** [comment]
@srish Thanks for the feedback! I've made the changes as requested.

**Comment by srish** [comment]
@brendajerop thanks a lot for your prompt response! I just merged your changes and made very minor fixes while merging them. 
As a next step, could you in your Sandbox add an example like https://www.mediawiki.org/wiki/API:Parsing_wikitext#Example_2:_Parse_a_section_of_a_page_and_fetch_its_table_data around this sample code? 

The ultimate goal would be to integrate it as a second example here:
https://www.mediawiki.org/wiki/API:Links. 

If you've any questions, ping me on Zulip.

**Comment by brendajerop** [comment]
@srish Thanks for merging my changes! I've added the example in my Sandbox [here](https://www.mediawiki.org/wiki/User:Jeropbrenda/Sandbox/API:Links)

**Pull request merged**
