### PR TITLE
added sample code for exturlusage

### PR DESCRIPTION
**Pull request by Olena23**
Modified README.md to include information and links for API: Exturlusage
Modified modules.json
Added code sample files for API: Exturlusage

### CODE REVIEW

**Comment by srish** [comment]
@Olena23 Overall your sample code looks great!

I would like to merge this code sample when your documentation is ready to go live on MediaWiki too. For reference see: https://www.mediawiki.org/wiki/User:Jeropbrenda/Sandbox/API:RecentChanges. I will also take another look at your code sample then.

**Comment by Olena23** [comment]
@srish thank you for the feedback! I compared my sandbox page with the link you gave and I don't see any differences in structure. This function has no deprecated parameters or additional notes.
https://www.mediawiki.org/wiki/User:Olena23/Sandbox/API:Exturlusage
If you can kindly point at any inconsistencies, I'll correct them

**Comment by srish** [comment]
@Olena23 Mostly looking good :) You can remove all the translation markers as they are generated by the software... read more about it here: https://wikimedia.zulipchat.com/#narrow/stream/180873-gsoc19-outreachy18/topic/Phab.3AT215682.20API.20documentation.20improvements/near/160061754. When you are done, I will review your document one more time.

**Comment by Olena23** [comment]
@srish I removed translation tags. Please check

**Comment by srish** [comment]
@Olena23 Thanks for your work on this! You can copy paste the content from https://www.mediawiki.org/wiki/User:Olena23/Sandbox/API:Exturlusage to https://www.mediawiki.org/wiki/API:Exturlusage :) Remember to add a note while publishing your changes, something like: "updated as per API documentation improvements project". Also, read my note about translation markers in https://www.mediawiki.org/w/index.php?title=User:Olena23/Sandbox/API:Exturlusage&action=history :)

**Pull request merged**
