### PR TITLE
API:Protect  & API:Langlinks

### PR DESCRIPTION
**Pull request by SupriyaSupugade**
Demo of `Protect` module: Demo to change the 'edit protection level' of a given page.
I have changed following files:

Demo of `Langlinks` module : Demo to gets a list of first 20 language links from the provided pages to other languages.

README.md
modules.json
python/protect.py
python/get_langlinks.py

`Protect` module: To change a page's protection level, token is required. Following are steps I followed to change page edit protection level.
step 1 : Retrieved a CSRF token by get request using API:Tokens with type=csrf
step 2 : Made a POST request to change a page 'edit protection level'

`Langlinks` module: GET request to list of first 20 language links with the localised language name.

@srish Plaese review. Thanks.! :)

### CODE REVIEW

**Comment by SupriyaSupugade** [comment]
@srish Following is the documentation link for `API:Protect`
https://www.mediawiki.org/wiki/User:Supriya_Supugade/Sandbox/API:Protect
Please review. Thank you.! :)

**Comment by SupriyaSupugade** [comment]
Thanks for the valuable feedback. :) I will make necessary changes.

**Comment by SupriyaSupugade** [comment]
@srish I have made new seperate PR for API:Protect [#104](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/104) and API:Langlinks [#105](https://github.com/wikimedia/MediaWiki-Action-API-Code-Samples/pull/105). Can I close this one?

**Comment by srish** [comment]
@SupriyaSupugade Ideally, you push the requested changes to the same PR and not start a different one. But, it is okay for this time.

**Pull request closed without merging**
