### PR TITLE
Add Sample code for API:Upload

### PR DESCRIPTION
**Pull request by mansiag**
I have added 2 sample codes for testing API:Upload
1) upload_directly.py - upload a file directly from the system
2) upload_from_url.py - upload a copy of a file elsewhere on the Web given by a URL
3) chunked_uploading.py - upload a file in chunks
Documentation of API:Upload : [link](https://www.mediawiki.org/wiki/User:Mansi29ag/Sandbox/API:Upload)
@srish please review. Thanks!

### CODE REVIEW

**Comment by mansiag** [comment]
Hey @srish please review this pull request. Thanks!

**Comment by mansiag** [comment]
I used test wiki endpoint for testing purposes but changed the endpoint to be kept in sample code because I thought the user who would refer to sample code for his project would not use test wiki endpoint but MediaWiki endpoint as he would have rights. Should I change to test wiki instead?

**Comment by mansiag** [comment]
@srish I have tested the code with many files but didn't got this error. Could you tell at what file input you got this error?

**Comment by mansiag** [comment]
@srish I have made the suggested changes in the files. I am left with the error you got in upload_file_in_chunks.py which I am unable to figure out. Also, bot upload permissions are not any special permissions, i.e. while creating bots user gets a chance to select all the features that his bot can do, and upload part is also covered in that. So maybe I should add how to get bot login id and password and the remaining steps will automatically get covered in it. What do you say?

**Comment by brendajerop** [comment]
Hello @mansiag :) I got the error that @srish has mentioned when the file extensions did not match. I think the file was a png but I had used jpg in the filename and chunks. Maybe try to mismatch the extensions and see if you'll get the error? 
Also, while testing, I may have uploaded [your file](https://test.wikipedia.org/wiki/File:Chunk_test10.png) without your permission...sorry:/ I can request that it be deleted.

**Comment by mansiag** [comment]
@brendajerop yes, you are right and thanks a lot. I really appreciate your help throughout. @srish Since this error can be made by a user, I would add it to the documentation. But, I think no changes are to be made in the code regarding this error.

**Comment by mansiag** [comment]
@srish I have refactored the code in `upload_file_in_chunks.py` as suggested. Thanks :)

**Comment by srish** [comment]
@mansiag Thanks a lot for your work on this! I've made some edits here https://www.mediawiki.org/wiki/User:Mansi29ag/Sandbox/API:Upload. But there is still some work remaining to be done. I've added a POST Request in first example: https://www.mediawiki.org/wiki/User:Mansi29ag/Sandbox/API:Upload#POST_Request and maybe you can replicate the same in other sections..

Might be also re-check this section: https://www.mediawiki.org/wiki/User:Mansi29ag/Sandbox/API:Upload#Response_3 and one thing for example you  could add is: a statement before Result 2 like you've done for other chunks..

One more thing to check would be whether this section https://www.mediawiki.org/wiki/User:Mansi29ag/Sandbox/API:Upload#Example_4:_Retrieving_upload_status is still valid for latest version of MediaWiki. From the note in the original documentation, it is unclear and I haven't investigated much.. might be worth checking.

Take a look at my comment above, and when you are done I would like to give a final read..

**Comment by mansiag** [comment]
@srish, Thanks a lot! :) I have also made the required changes in the documentation.

- Tested the working of `retrieving_upload_status` and yes, it is still working. I have added the code for it as a function in upload_file_in_chunks.py only as this status is for chunked uploading only. I haven't created a pull request for the changes but added the changed code in documentation. Also added its response code and post request.
-  Added post request for all the sections.

**Pull request merged**
