### PR TITLE
API- Pagepropnames

### PR DESCRIPTION
**Pull request by aashuli**
Thank You @srish for replying on the previous pull request. Here are the changes you asked and the documentation changes are updated on https://www.mediawiki.org/wiki/User:Aashuli/Sandbox/API:Pagepropnames . Please review the changes .

### CODE REVIEW

**Comment by aashuli** [comment]
@srish Sorry I will consider this for the next time and thank you for your review. I have made the required changes please give your feedback.

**Comment by srish** [comment]
@aashuli Thanks a lot for your work on this! I've made minor fixes to: https://www.mediawiki.org/wiki/User:Aashuli/Sandbox/API:Pagepropnames and it is ready now to be moved to the main namespace on MediaWiki.org :) Remember to leave a note when you publish your changes: "updated as per the 'improving the top 50 action APIs' project". If you've any questions, ask in the Zulip chat, someone might be able to help!

**Comment by srish** [comment]
@aashuli just noticed you are not on Zulip chat yet: https://wikimedia.zulipchat.com/#narrow/stream/180873-gsoc19-outreachy18/topic/Phab.3AT215682.20API.20documentation.20improvements :)

**Comment by aashuli** [comment]
@srish I am there on zulip by the username Aashuli Kabra.  Can you tell me the prodcedure to publish my changes, also what all is to be mentioned in project timeline required for final application.

**Pull request merged**
