### PR TITLE
Sample code for API: Options module

### PR DESCRIPTION
**Pull request by reefagirl**
I wrote sample code to change user options which is done via the Options module which can be viewed at https://www.mediawiki.org/wiki/API:Options.

As the code wasn't in the current repository or in the wiki page, I wrote a sample code for it.

I tested it by obtaining credentials via Special:BotPasswords, for a login token.

### CODE REVIEW

**Comment by silkypriya** [comment]
Based on #55

**Comment by srish** [comment]
@reefagirl Thanks for your contribution to this project! But, this is not related to any microtask that I've added to the task description on Phabricator [T215682](https://phabricator.wikimedia.org/T215682) :-/ 

I will try to create a microtask around the `Options` module and then will get back to you in a day or so! 

In the future, before starting work on a topic /  sending a pull request, I would appreciate it if you discuss it with me on Zulip or Phabricator. That way I can verify if the particular contribution would be helpful or not for the project at the moment.

**Comment by reefagirl** [comment]
My apologies, I will make sure to discuss topics before starting them in future.

Thank you for your help, I greatly appreciate it.

**Comment by srish** [comment]
@reefagirl I don't know your Phabricator username, but I've added your Github username next to `API:Options` module in the task description https://phabricator.wikimedia.org/T215682. I will be reviewing your pull request soon!

**Comment by reefagirl** [comment]
Thank you, I edited the Phabricator task description with my Phabricater username :) 
Kindly let me know your feedback and suggested improvements.
I will start creating the API Documentation page in my sandbox as instructed in Phabricator.

**Comment by reefagirl** [comment]
Thank you. I will do the updates and commit them soon :)

**Comment by reefagirl** [comment]
@srish thank you for your feedback. I made the commits to update the code.

The documentation I created can be found at [https://www.mediawiki.org/wiki/User:Areefat/Sandbox/API:Options](https://www.mediawiki.org/wiki/User:Areefat/Sandbox/API:Options)

Appreciate the opportunity to contribute!

**Comment by srish** [comment]
@reefagirl Thanks a lot for your work! Here is first round of feedback https://www.mediawiki.org/wiki/Topic:Uv9lt04gmcv10ggl :)

**Comment by reefagirl** [comment]
@srish Thank you for taking your time to provide feedback.
I made the changes accordingly. I was a bit confused with the parameters section, I referred to the page suggested as well as a few other pages with a parameters section and edited it. If there are any changes let me know.
Hope it is as expected.
Thank you :)

**Comment by srish** [comment]
@reefagirl Mostly looking good :) You can remove all the translation markers as they are generated by the software... read more about it here: https://wikimedia.zulipchat.com/#narrow/stream/180873-gsoc19-outreachy18/topic/Phab.3AT215682.20API.20documentation.20improvements/near/160061754. When you are done, I will review your document one more time.

**Comment by reefagirl** [comment]
@srish Thank you,
I removed all the translation markers :)
Appreciate all the help.

**Comment by srish** [comment]
Thanks a lot for your work on this! I've made some fixes to documentation here:
https://www.mediawiki.org/wiki/User:Areefat/Sandbox/API:Options

You can copy paste the changes to MediaWiki.org. When you publish your changes make sure to say in the comment: "updated as per the improving the action API documentation project". For reference check following page's history as it recently got updated: https://www.mediawiki.org/w/index.php?title=API:Move&action=history. Let me know if you've any trouble while doing so :)

**Comment by reefagirl** [comment]
Thank you @srish , very grateful to be a part of this project.
I made the changes on MediaWiki.org :)
I would love to make more contributions to this project and hope to get the opportunity to do so.

**Pull request merged**
